laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@logo')->name('logo');
    Route::get('home', 'HomeController@index')->name('home');
    Route::get('projetos/detalhes/{projeto}', 'ProjetosController@show')->name('projetos.show');
    Route::get('projetos/{categoria}/{subcategoria?}', 'ProjetosController@index')->name('projetos');
    Route::get('perfil', 'PerfilController@index')->name('perfil');
    Route::get('clipping', 'ClippingController@index')->name('clipping');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('projetos/categorias', 'ProjetosCategoriasController', ['parameters' => ['categorias' => 'categorias_projetos']]);
        Route::resource('projetos/categorias.subcategorias', 'ProjetosSubcategoriasController', ['parameters' => ['categorias' => 'categorias_projetos', 'subcategorias' => 'subcategorias_projetos']]);
        Route::get('fetch-subcategorias/{id}', function($id) {
            $categoria = \App\Models\ProjetoCategoria::findOrFail($id);
            return $categoria->subcategorias->lists('titulo', 'id');
        });
		Route::resource('projetos', 'ProjetosController');
		Route::get('projetos/{projetos}/imagens/clear', [
			'as'   => 'painel.projetos.imagens.clear',
			'uses' => 'ProjetosImagensController@clear'
		]);
		Route::resource('projetos.imagens', 'ProjetosImagensController', ['parameters' => ['imagens' => 'imagens_projetos']]);
		Route::resource('clipping', 'ClippingController');
		Route::get('clipping/{clipping}/imagens/clear', [
			'as'   => 'painel.clipping.imagens.clear',
			'uses' => 'ClippingImagensController@clear'
		]);
		Route::resource('clipping.imagens', 'ClippingImagensController', ['parameters' => ['imagens' => 'imagens_clipping']]);
		Route::resource('arquitetos', 'ArquitetosController');
		Route::resource('perfil', 'PerfilController', ['only' => ['index', 'update']]);
		Route::resource('banners', 'BannersController');
		Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);

        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Models/Projeto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Helpers\CropImage;

use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;

class Projeto extends Model implements SluggableInterface
{
    use SluggableTrait;

    protected $sluggable = [
        'build_from' => 'titulo',
        'save_to'    => 'slug',
        'on_update'  => true
    ];

    protected $table = 'projetos';

    protected $guarded = ['id'];

    public function scopeOrdenados($query)
    {
        return $query->orderBy('ordem', 'ASC')->orderBy('id', 'DESC');
    }

    public function scopeSlug($query, $slug)
    {
        return $query->whereSlug($slug);
    }

    public function scopeCategoria($query, $categoria_id)
    {
        return $query->where('projetos_categoria_id', $categoria_id);
    }

    public function scopeSubcategoria($query, $subcategoria_id)
    {
        return $query->where('projetos_subcategoria_id', $subcategoria_id);
    }

    public function categoria()
    {
        return $this->belongsTo('App\Models\ProjetoCategoria', 'projetos_categoria_id');
    }

    public function subcategoria()
    {
        return $this->belongsTo('App\Models\ProjetoSubcategoria', 'projetos_subcategoria_id');
    }

    public function imagens()
    {
        return $this->hasMany('App\Models\ProjetoImagem', 'projeto_id')->ordenados();
    }

    public static function upload_capa()
    {
        return CropImage::make('capa', [
            'width'  => 1300,
            'height' => 280,
            'path'   => 'assets/img/projetos/'
        ]);
    }
}

laravel/app/Http/Controllers/Painel/ProjetosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ProjetosRequest;
use App\Http\Controllers\Controller;

use App\Models\Projeto;
use App\Models\ProjetoCategoria;

class ProjetosController extends Controller
{
    private $categorias;

    public function __construct()
    {
        $this->categorias = ProjetoCategoria::ordenados()->lists('titulo', 'id');
    }

    public function index(Request $request)
    {
        $categorias = $this->categorias;
        $filtro     = $request->query('filtro');

        if (ProjetoCategoria::find($filtro)) {
            $registros = Projeto::where('projetos_categoria_id', $filtro)->ordenados()->get();
        } else {
            $registros = Projeto::leftJoin('projetos_categorias as cat', 'cat.id', '=', 'projetos_categoria_id')
                ->orderBy('cat.ordem', 'ASC')
                ->orderBy('cat.id', 'DESC')
                ->select('projetos.*')
                ->ordenados()->get();
        }

        return view('painel.projetos.index', compact('categorias', 'registros', 'filtro'));
    }

    public function create()
    {
        $categorias = $this->categorias;

        return view('painel.projetos.create', compact('categorias'));
    }

    public function store(ProjetosRequest $request)
    {
        try {

            $input = $request->all();

            if (request('projetos_subcategoria_id') === '') {
                $input['projetos_subcategoria_id'] = null;
            }

            if (isset($input['capa'])) $input['capa'] = Projeto::upload_capa();

            Projeto::create($input);

            return redirect()->route('painel.projetos.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Projeto $registro)
    {
        $categorias = $this->categorias;

        return view('painel.projetos.edit', compact('registro', 'categorias'));
    }

    public function update(ProjetosRequest $request, Projeto $registro)
    {
        try {

            $input = $request->all();

            if (request('projetos_subcategoria_id') === '') {
                $input['projetos_subcategoria_id'] = null;
            }

            if (isset($input['capa'])) $input['capa'] = Projeto::upload_capa();

            $registro->update($input);

            return redirect()->route('painel.projetos.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Projeto $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.projetos.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/ProjetosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Models\Projeto;
use App\Models\ProjetoCategoria;
use App\Models\ProjetoSubcategoria;

class ProjetosController extends Controller
{
    public function index(ProjetoCategoria $categoria, ProjetoSubcategoria $subcategoria)
    {
        if ($subcategoria->exists && ! $categoria->subcategorias->contains($subcategoria)) {
            abort('404');
        }

        return view('frontend.projetos.index', compact('categoria', 'subcategoria'));
    }

    public function show(Projeto $projeto)
    {
        return view('frontend.projetos.show', compact('projeto'));
    }
}

laravel/resources/views/painel/projetos/subcategorias/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Projetos / {{ $categoria->titulo }} /</small> Adicionar Subategoria</h2>
    </legend>

    {!! Form::open(['route' => ['painel.projetos.categorias.subcategorias.store', $categoria]]) !!}

        @include('painel.projetos.subcategorias.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/projetos/subcategorias/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Projetos / {{ $categoria->titulo }} /</small> Editar Subcategoria</h2>
    </legend>

    {!! Form::model($subcategoria, [
        'route'  => ['painel.projetos.categorias.subcategorias.update', $categoria->id, $subcategoria->id],
        'method' => 'patch'])
    !!}

    @include('painel.projetos.subcategorias.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/projetos/subcategorias/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('titulo', 'Título') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.projetos.categorias.subcategorias.index', $categoria) }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/projetos/subcategorias/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <a href="{{ route('painel.projetos.categorias.index') }}" title="Voltar para Categorias" class="btn btn-sm btn-default">
        &larr; Voltar para Categorias
    </a>

    <legend>
        <h2>
            <small>Projetos / {{ $categoria->titulo }} /</small> Subcategorias

            <a href="{{ route('painel.projetos.categorias.subcategorias.create', $categoria) }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Subcategoria</a>
        </h2>
    </legend>

    @if(!count($subcategorias))
    <div class="alert alert-warning" role="alert">Nenhuma subcategoria cadastrada.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-sortable" data-table="projetos_subcategorias">
        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Título</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($subcategorias as $subcategoria)
            <tr class="tr-row" id="{{ $subcategoria->id }}">
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                <td>{{ $subcategoria->titulo }}</td>
                <td class="crud-actions">
                    {!! Form::open(array('route' => array('painel.projetos.categorias.subcategorias.destroy', $categoria, $subcategoria), 'method' => 'delete')) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.projetos.categorias.subcategorias.edit', [$categoria, $subcategoria]) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @endif

@endsection